In [1]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [2]:
import numpy as np

print(np.__version__)

1.24.3


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [7]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [8]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


In [9]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
Sure! Let's break down the code step by step:

### Code
```python
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])
```

### Explanation

1. **Importing NumPy**:
   ```python
   import numpy as np
   ```
   - This imports the NumPy library and gives it the alias `np`. NumPy is a library used for numerical operations and array manipulation.

2. **Creating a 2D Array**:
   ```python
   arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
   ```
   - `np.array()` creates a NumPy array from the given list of lists. 
   - The resulting array `arr` looks like this:
     ```
     [[ 1,  2,  3,  4,  5],
      [ 6,  7,  8,  9, 10]]
     ```

3. **Slicing the Array**:
   ```python
   print(arr[0:2, 1:4])
   ```
   - `arr[0:2, 1:4]` is used to slice the array.
   - The syntax `arr[start_row:end_row, start_col:end_col]` is used to select a subarray.
   - **`0:2`** selects rows from index 0 up to, but not including, index 2. So it selects the first and second rows.
   - **`1:4`** selects columns from index 1 up to, but not including, index 4. So it selects the columns with indices 1, 2, and 3.

   Applying these slices:
   - For rows: index 0 and 1 are included, so we have:
     ```
     [[ 1,  2,  3,  4,  5],
      [ 6,  7,  8,  9, 10]]
     ```
   - For columns: index 1 to 3 are included, so we get:
     ```
     [[ 2,  3,  4],
      [ 7,  8,  9]]
     ```

   The final output of the code:
   ```python
   [[2, 3, 4],
    [7, 8, 9]]
   ``

In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[1 2 3 4 5]


In [1]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print("x represents the 2-D array:")
  print(x)

x represents the 2-D array:
[[1 2 3]
 [4 5 6]]
x represents the 2-D array:
[[ 7  8  9]
 [10 11 12]]


In [2]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [6]:
import numpy as np
arr =  np.array([[1, 2, 3],[4, 5, 6]])
for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
4
6


In [7]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

for idx, x in np.ndenumerate(arr):
  print(idx, x)


(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8


In [16]:
import numpy as np

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6 7 8]


In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [19]:
import numpy as np

arr = ([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12],[13, 14, 15],[16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [21]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = arr[[True, False, True, False]]

print(x)


[41 43]


In [25]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filtered_arr = []

for element in arr:
    if element > 42:
        filtered_arr.append(True)
    else:
        filtered_arr.append(False)
        
newarr = arr[filtered_arr]

print(filtered_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [26]:
from numpy import random

arr1 = random.randint(50)

arr2 = random.rand()

print(arr1)
print(arr2)

11
0.7293766867441303


In [27]:
from numpy import random

arr1  = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

arr2 = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(arr1)
print(arr2)

[[5 7 5 3 5]
 [3 3 7 3 5]
 [5 7 7 7 3]]
[7 7 5 5 7 7 3 5 5 7 5 7 3 7 5 7 7 7 7 7 7 3 5 7 5 7 7 7 7 7 5 5 5 7 3 3 3
 7 7 7 7 7 7 7 5 7 7 5 5 3 3 7 7 7 5 7 7 7 5 5 5 7 3 5 7 5 7 5 7 3 5 3 3 7
 5 7 7 5 5 7 5 7 7 5 7 5 7 3 7 7 7 5 5 5 5 3 7 7 5 7]


In [28]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[4 1 3 5 2]


In [29]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))

[2 3 5 4 1]
